PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX stabs-d: <stabs:scope:data/>

WITH <https://ld.staatsarchiv.bs.ch/graph/source>

DELETE
WHERE {
    ?s a rico:RecordResource .
    ?s stabs-d:PHYSISCHE_BESCHAFFENHEIT ?pB .
}