PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX stabs-d: <stabs:scope:data/>

WITH <https://ld.staatsarchiv.bs.ch/graph/source>

DELETE { ?s ?p ?o }
WHERE { ?s ?p ?o .
  VALUES (?p ?o) {
    (UNDEF rico:RecordResource)
    (stabs-d:ID_NR UNDEF)
    (stabs-d:PHYSISCHE_BESCHAFFENHEIT UNDEF)
  }
}
