PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>

WITH <https://ld.staatsarchiv.bs.ch/graph/source>
DELETE {?s rico:expressedDate ?o}
INSERT {?s rico:expressedDate ?1Date}
WHERE { 
  ?s rico:expressedDate ?o .
  filter regex(?o, '\r\n\r\n')
  BIND (strbefore(?o, '\r\n\r\n') as ?1Date)
}